-- Settings panel copy: every text of the panel, by row key.
-- GENERATED by tools/copy2lua.js from the copy document; do not edit by hand.
local _, ns = ...
local L = ns.L

ns.Copy = {
    modules = {
        ab = {
            desc = L["Blizzard's action bars in FlareUI's style."],
            editButton = L["Edit bars in Edit Mode"],
            title = L["Action Bars"],
        },
        about = {
            desc = L["Version, credits and what's new on FlareUI."],
            title = L["About"],
        },
        adv = {
            desc = L["Save FlareUI's settings under a name, switch between them, or start fresh."],
            title = L["Profiles"],
        },
        au = {
            desc = L["Your buffs and debuffs in FlareUI's style."],
            editButton = L["Edit Auras in Edit Mode"],
            title = L["Buffs & Debuffs"],
        },
        ch = {
            desc = L["A cleaner chat frame with a customisable header."],
            title = L["Chat"],
        },
        dm = {
            banner = L["Blizzard's damage meter is off. FlareUI's meter needs it."],
            bannerButton = L["Turn it on"],
            desc = L["Blizzard's damage meter in a FlareUI frame, with a threat view tab."],
            title = L["Damage Meter"],
        },
        mm = {
            desc = L["A square minimap with some tricks under the hood."],
            title = L["Minimap"],
        },
        qol = {
            desc = L["Small helpers that save you some clicks."],
            tabs = { L["Gameplay"], L["Interface"], L["Advanced"] },
            title = L["Quality of Life"],
        },
        qt = {
            desc = L["FlareUI's own functional quest tracker."],
            editButton = L["Edit Tracker in Edit Mode"],
            title = L["Quest Tracker"],
        },
        rb = {
            desc = L["Useful resource tracking bars you can set anywhere."],
            editButton = L["Edit Resources in Edit Mode"],
            title = L["Resource Bars"],
        },
        rm = {
            desc = L["A ring of spells, items, macros and more. Hold keybind, point, release."],
            tabs = { L["Editor"], L["Keybinds"], L["Options"] },
            title = L["Radial Menu"],
        },
        tt = {
            desc = L["Cleaner tooltips with coloured borders and mouse anchoring."],
            title = L["Tooltips"],
        },
        uf = {
            desc = L["Player, target, focus, pet and party frames in FlareUI's style."],
            editButton = L["Edit Frames in Edit Mode"],
            editNote = L["Size, health text, portrait, auras and icons are set in Edit Mode."],
            title = L["Unit Frames"],
        },
    },
    rows = {
        ["ab.bar.group"] = {
            choices = { L["None"], L["1"], L["2"], L["3"] },
            desc = L["Bars in the same group fade in and out together: point at one and they all appear. The group shares one Show Condition choice."],
            label = L["Fade group"],
            tip = L["Put your bottom bars in one group and your side bars in another."],
        },
        ["ab.bar.show"] = {
            choices = { L["Always"], L["Mouseover"], L["Combat"], L["Combat + Target"], L["Combat + Attackable Target"] },
            desc = L["When this bar appears."],
            label = L["Show Condition"],
            tip = L["Hovering the bar always shows it."],
        },
        ["ab.fade"] = {
            desc = L["Bars 1 to 8, the pet bar and the stance bar each have a Show choice and a fade group in their Edit Mode dialog."],
            info = L["Fade Options"],
            label = L["Use Edit Mode to set fading and fade groups for each bar"],
            section = "ab.fadeOptions",
            tip = L["Bars in the same fade group fade in and out together, based on the same show conditional."],
        },
        ["ab.fcmBars"] = {
            desc = L["The bars you pick become a cooldown display. They can't be clicked and show only by the conditional below."],
            label = L["Bars"],
            section = "ab.fakeCooldownManager",
            tip = L["Enable Fake CM setup mode and put the spells you want to track on the bars you selected here."],
        },
        ["ab.fcmEnable"] = {
            desc = L["Turns some of your action bars into a cooldown display, like Blizzard's Cooldown Manager."],
            label = L["Enable"],
            section = "ab.fakeCooldownManager",
        },
        ["ab.fcmSetup"] = {
            desc = L["Shows the Fake CM bars and lets you click them, so you can arrange spells. Ends when you leave it or reload."],
            label = L["FCM Setup Mode"],
            section = "ab.fakeCooldownManager",
            tip = L["`/fui cm` does the same."],
        },
        ["ab.fcmShow"] = {
            choices = { L["Combat"], L["Combat + Target"], L["Combat + Attackable Target"], L["Always"] },
            desc = L["When the Fake CM bars appear. In setup mode they always show."],
            label = L["Show Condition"],
            section = "ab.fakeCooldownManager",
        },
        ["ab.hideBlizzardElements"] = {
            chips = { L["Micro menu"], L["Bag bar"], L["Pet bar"], L["Stance bar"], L["Totem bar"], L["Possess bar"], L["Gryphons"], L["Raid manager"] },
            desc = L["Hides any of these Blizzard bars for good. They become completely invisible, including in edit mode."],
            tags = { "gryphons", "lions", "wyverns", "end caps", "art", "micro menu", "bags" },
        },
        ["ab.hideKeybinds"] = {
            desc = L["Removes the key labels from every button, for players who know their keys by heart."],
            label = L["Hide keybind text"],
            section = "ab.buttons",
        },
        ["ab.hideMacroText"] = {
            desc = L["Removes the macro names from buttons that hold a macro."],
            label = L["Hide macro text"],
            section = "ab.buttons",
        },
        ["ab.procGlow"] = {
            desc = L["Abilities that light up after something happens glow on your bars: Overpower, Revenge, Riposte, Counterattack, Mongoose Bite, Execute, Hammer of Wrath and others."],
            label = L["Ability Proc glow"],
            section = "ab.buttons",
        },
        ["ab.statusColours"] = {
            desc = L["Buttons turn red when the target is out of range and blue when you're out of mana or energy. Spells you can't use at the moment turn grey."],
            label = L["Status colouring"],
            section = "ab.buttons",
        },
        ["ab.xpBar"] = {
            desc = L["One slim bar for experience and reputation (or honor), placed wherever you like in Edit Mode."],
            label = L["FlareUI XP bar"],
            reload = true,
            section = "ab.experience",
            tip = L["Hover the bar to see the values."],
        },
        ["about.commands"] = {
            kind = "text",
            label = L["Slash commands"],
            section = "about.credits",
            text = L["`/fui` open settings. `/fui cm` Fake CM setup mode. `/fui pad` switch gamepad mode on/off."],
        },
        ["about.credits"] = {
            kind = "text",
            label = L["Credits"],
            section = "about.credits",
            text = L["• Doggie art by |cffffd100Clari Turela|r.\n• |cffffd100sampconrad|r for the help with aura frames.\n• Licences for libraries and code FlareUI builds on are in its LICENSES folder."],
        },
        ["about.links"] = {
            kind = "text",
            label = L["Links"],
            section = "about.yourFriendlyUiOverhowl",
            text = L["Click an icon to copy its link."],
        },
        ["about.thanks"] = {
            kind = "text",
            label = L["Thank you"],
            section = "about.yourFriendlyUiOverhowl",
            text = L["Hope you enjoy FlareUI! If you found bugs or have feature ideas, give me a holler through the links below."],
        },
        ["adv.manage"] = {
            desc = L["New starts a profile from FlareUI's defaults.\nDuplicate starts one with the settings of the profile in use.\nDelete removes a profile you aren't using.\n"],
            info = L["Manage profiles"],
            label = L["Manage profiles"],
            tip = L["New and Duplicate switch to the new profile, which reloads the interface."],
        },
        ["adv.profiles"] = {
            desc = L["The profile in use.\n"],
            info = L["Profiles"],
            label = L["Active profile"],
            tip = L["Switching profiles reloads the interface."],
        },
        ["adv.reset"] = {
            desc = L["Puts every FlareUI setting back to default. Your Blizzard settings aren't touched."],
            label = L["Reset FlareUI"],
            section = "adv.reset",
        },
        ["au.*.perRow"] = {
            desc = L["The size of the icons and how many sit in a row."],
            label = L["Icons per row"],
        },
        ["au.*.size"] = {
            desc = L["The size of the icons and how many sit in a row."],
            label = L["Icon size"],
        },
        ["au.shape"] = {
            choices = { L["Round"], L["Square"] },
            desc = L["The shape of the icons in the buff and debuff frames."],
            label = L["Icon shape"],
        },
        ["au.timer"] = {
            choices = { L["Under the icon"], L["Bottom of the icon"], L["Middle of the icon"], L["None"] },
            desc = L["Where the time left shows in the buff and debuff frames."],
            label = L["Timer"],
        },
        ["ch.combatLog"] = {
            desc = L["Removes the Combat Log tab."],
            label = L["Hide combat log"],
        },
        ["ch.copyLinks"] = {
            desc = L["Click a web link in chat to get it in a box you can copy from."],
            label = L["Copy chat links"],
        },
        ["ch.editBox"] = {
            choices = { L["Inside"], L["Below"], L["Above"] },
            desc = L["Where you type. Below and Above keep the latest messages visible."],
            label = L["Edit box"],
        },
        ["ch.fade"] = {
            desc = L["Chat fades after a few seconds and comes back for new messages, while you type, or when you point at it."],
            label = L["Fade chat"],
        },
        ["ch.headerButtons"] = {
            chips = { L["Social"], L["Chat channels"], L["Chat menu"], L["Volume"] },
            desc = L["The buttons in the chat header. Turn off the ones you don't use."],
            label = L["Header buttons"],
            section = "ch.header",
            tip = L["You can drag buttons to reorder them."],
        },
        ["ch.headerHelp"] = {
            kind = "text",
            label = L["How the header works"],
            section = "ch.howTo",
            text = L["• Drag a tab or a header button to reorder them to your preference.\n• Scroll the mouse wheel over the header to show more tabs when there are too many to fit."],
        },
        ["ch.history"] = {
            desc = L["Keeps your chat history after a reload or relog."],
            label = L["Save history"],
        },
        ["ch.noBubbles"] = {
            desc = L["Turns chat bubbles off inside dungeons, raids and battlegrounds."],
            label = L["No bubbles in instances"],
        },
        ["ch.opacity"] = {
            desc = L["How dark you want the background of the chat to be."],
            label = L["Frame Opacity"],
        },
        ["dm.buttonsHelp"] = {
            kind = "text",
            label = L["Header buttons note"],
            section = "dm.extras",
            text = L["• A Countdown button shows while you're in a group.\n• A Ready check button shows when you lead or assist a group."],
        },
        ["dm.matchChat"] = {
            desc = L["The meter takes the chat frame's width and height."],
            label = L["Match chat size"],
        },
        ["dm.mouseover"] = {
            desc = L["Hover the Damage Meter panel to reveal it."],
            label = L["Show on mouseover"],
        },
        ["dm.opacity"] = {
            desc = L["How dark you want the background of the damage meter to be."],
            label = L["Frame Opacity"],
        },
        ["dm.threatCombat"] = {
            desc = L["Switches to the threat view when combat starts, and back when it ends."],
            label = L["Threat view in combat"],
        },
        ["dm.threatKey"] = {
            desc = L["A key that switches the meter between damage and threat."],
            label = L["Toggle Threat Meter"],
            tip = L["Right-click the key to clear it."],
        },
        ["dm.visibility"] = {
            choices = { L["Always visible"], L["In combat"], L["Hidden"], L["In group"] },
            desc = L["When the Damage Meter shows up on the screen."],
            label = L["Visibility"],
        },
        ["mm.bag"] = {
            desc = L["Every addon's minimap button in one drawer."],
            label = L["Addon button drawer"],
            tip = L["Click the day/night badge to open it."],
        },
        ["mm.zoom"] = {
            choices = { L["Off"], L["5 s"], L["10 s"], L["30 s"] },
            desc = L["Zooms the minimap back out a few seconds after you zoom in."],
            label = L["Auto zoom out"],
        },
        ["qol.camera"] = {
            desc = L["Lets the camera zoom out further, and zoom faster."],
            label = L["Better camera"],
            section = "qol.camera",
        },
        ["qol.delete"] = {
            desc = L["Fills in DELETE when you try to destroy a valuable item."],
            label = L["Auto-type DELETE"],
            section = "qol.convenience",
        },
        ["qol.durability"] = {
            desc = L["Warns you when your gear drops below 50% durability."],
            label = L["Durability warning"],
            section = "qol.vendor",
        },
        ["qol.fastLoot"] = {
            desc = L["Loots everything at once, without the loot window showing."],
            label = L["Faster auto loot"],
            section = "qol.looting",
        },
        ["qol.hideClutter"] = {
            chips = { L["Error messages"], L["Zone text"], L["Party title"], L["Contextual tips"] },
            desc = L["Hides Blizzard messages and pop-ups you don't need."],
        },
        ["qol.move"] = {
            desc = L["Drag any Blizzard window by its header. Loot rolls and toasts can be moved in Edit Mode."],
            label = L["Move any window"],
            section = "qol.windows",
            tip = L["Shift + right-click a window's header to reset its position."],
        },
        ["qol.npCombo"] = {
            desc = L["Combo point gems under your target's nameplate."],
            label = L["Combo points"],
            section = "qol.nameplates",
        },
        ["qol.npLevel"] = {
            desc = L["Hide the level box to the right of Blizzard's nameplates."],
            label = L["Hide level"],
            section = "qol.nameplates",
        },
        ["qol.npQuest"] = {
            desc = L["A small quest mark on enemies you need for a quest."],
            label = L["Quest objectives"],
            section = "qol.nameplates",
        },
        ["qol.repair"] = {
            desc = L["Repairs your gear whenever you open a vendor that can."],
            label = L["Auto repair"],
            section = "qol.vendor",
        },
        ["qol.sellJunk"] = {
            desc = L["Sells your grey items whenever you open a vendor."],
            label = L["Auto sell junk"],
            section = "qol.vendor",
        },
        ["qol.source"] = {
            desc = L["Every other character copies its settings from this one."],
            label = L["Make this character the source"],
            section = "qol.syncBlizzUi",
        },
        ["qol.sync"] = {
            desc = L["Copies Blizzard's configuration, Edit Mode layout, chat and bag settings from one character to all others."],
            label = L["Sync Blizz UI"],
            reload = true,
            section = "qol.syncBlizzUi",
        },
        ["qol.trainAll"] = {
            desc = L["A Train All button at class and profession trainers."],
            label = L["Train all"],
            section = "qol.convenience",
        },
        ["qol.way"] = {
            desc = L["Type /way and coordinates to place a map pin and track it."],
            label = L["/way map pins"],
            section = "qol.convenience",
            tip = L["/way 45 60, or /way Elwynn Forest 45 60."],
        },
        ["qt.minCombat"] = {
            desc = L["The tracker shrinks to its header there, and comes back when you leave."],
            label = L["Combat"],
            section = "qt.minimizeIn",
        },
        ["qt.minInstances"] = {
            desc = L["The tracker shrinks to its header there, and comes back when you leave."],
            label = L["Instances"],
            section = "qt.minimizeIn",
        },
        ["qt.minimizeKey"] = {
            desc = L["A key that shrinks the tracker to its header, or opens it again."],
            label = L["Minimize Tracker Keybind"],
            section = "qt.minimizeIn",
            tip = L["Right-click the key to clear it."],
        },
        ["qt.opacity"] = {
            desc = L["How dark you want the background of the quest tracker to be."],
            label = L["Frame Opacity"],
        },
        ["qt.size"] = {
            label = L["Width · Max height"],
        },
        ["qt.sort"] = {
            choices = { L["By zone"], L["By distance"], L["By level"] },
            desc = L["By zone: quests grouped under their zone, the zone you're in first.\nBy distance: the nearest quest first, updating as you move.\nBy level: the lowest level quest first, the highest last."],
            label = L["Objective Sorting"],
        },
        ["rb.*.fsr"] = {
            desc = L["After you spend mana, a spark crosses the bar for five seconds. Spirit regeneration comes back when it ends."],
            label = L["Five-second rule"],
        },
        ["rb.*.show"] = {
            choices = { L["Always"], L["Combat"], L["Combat + Target"], L["Combat + Attackable Target"] },
            desc = L["When the bar appears."],
            label = L["Show Condition"],
        },
        ["rb.*.size"] = {
            desc = L["The bar's size."],
            label = L["Width · Height"],
        },
        ["rb.combo"] = {
            desc = L["Your combo points as a segmented bar."],
            label = L["Combo points"],
            section = "rb.bars",
        },
        ["rb.combo.classic"] = {
            desc = L["Blizzard's classic gems instead of FlareUI's strip."],
            label = L["Classic combo points"],
        },
        ["rb.health"] = {
            desc = L["Your health as a separate bar."],
            label = L["Health"],
            section = "rb.bars",
        },
        ["rb.health.text"] = {
            choices = { L["None"], L["Percent"], L["Value"], L["Value + Percent"] },
            desc = L["The numbers on the health bar."],
            label = L["Health text"],
        },
        ["rb.mana"] = {
            desc = L["Shows your mana bar while you are in cat or bear forms."],
            label = L["Druid Mana"],
            section = "rb.bars",
        },
        ["rb.power"] = {
            desc = L["Your main power: rage, energy, mana or focus."],
            label = L["Power"],
            section = "rb.bars",
        },
        ["rb.swingMain"] = {
            desc = L["A timer for each weapon's next swing."],
            label = L["Main-hand swing"],
            section = "rb.bars",
        },
        ["rb.swingOff"] = {
            desc = L["A timer for each weapon's next swing."],
            label = L["Off-hand swing"],
            section = "rb.bars",
        },
        ["rb.swingRanged"] = {
            desc = L["A timer for each weapon's next swing."],
            label = L["Ranged swing"],
            section = "rb.bars",
        },
        ["rm.keys"] = {
            desc = L["Each bind opens a radial on this character. Right-click a key to clear it."],
            empty = L["No keybinds yet. Add one to open a radial."],
            label = L["Keybinds"],
            tip = L["Combinations with Alt, Ctrl and Shift work too."],
        },
        ["rm.macroCreate"] = {
            desc = L["Open a radial from actions bar or other radials. Macro conditionals work.\n\nPressing the macro opens the radial. Click or press the macro to use a button.\nRight-click or Escape closes it."],
            done = L["Macro \"{name}\" created and on your cursor. Drop it on a bar."],
            errorInCombat = L["You can't create macros in combat."],
            errorMacrosFull = L["Your macro list is full. Delete one and try again."],
            label = L["Create macro"],
            section = "rm.radialMacros",
            tip = L["reate macro makes a macro for the selected radial at your cursor."],
        },
        ["rm.macroRadial"] = {
            desc = L["Open a radial from action bars or other radials. Macro conditionals work.\n\nPressing the macro opens the radial. Click or press the macro to use a button.\nRight-click or Escape closes it."],
            label = L["Radial"],
            section = "rm.radialMacros",
            tip = L["Create macro makes a macro for the selected radial at your cursor."],
        },
        ["rm.names"] = {
            desc = L["The button you point at shows the name of its action."],
            label = L["Show button names"],
            section = "rm.look",
        },
        ["rm.pad"] = {
            desc = L["R3 opens the main radial and picks a button. The ping menu moves to L3."],
            label = L["Controller support"],
            section = "rm.controller",
        },
        ["tt.anchor"] = {
            choices = { L["Default"], L["Cursor"] },
            desc = L["Where every tooltip appears: Blizzard's corner, or next to your mouse."],
            label = L["Anchor"],
        },
        ["tt.borders"] = {
            desc = L["The border takes the colour of a player's class, a creature's reaction, or an item's quality."],
            label = L["Coloured borders"],
        },
        ["tt.classNames"] = {
            desc = L["Player names are shown in their class colour."],
            label = L["Class-coloured names"],
        },
        ["tt.ids"] = {
            desc = L["Adds item and spell IDs to tooltips."],
            label = L["Show IDs"],
        },
        ["tt.showBars"] = {
            choices = { L["Always"], L["Hide in combat"], L["Never"] },
            desc = L["When tooltips appear for what you point at."],
            label = L["On action bars"],
            section = "tt.showTooltips",
            tip = L["Hold Shift to see a hidden tooltip."],
        },
        ["tt.showFrames"] = {
            choices = { L["Always"], L["Hide in combat"], L["Never"] },
            desc = L["When tooltips appear for what you point at."],
            label = L["On unit frames"],
            section = "tt.showTooltips",
            tip = L["Hold Shift to see a hidden tooltip."],
        },
        ["tt.showWorld"] = {
            choices = { L["Always"], L["Hide in combat"], L["Never"] },
            desc = L["When tooltips appear for what you point at."],
            label = L["In the world"],
            section = "tt.showTooltips",
            tip = L["Hold Shift to see a hidden tooltip."],
        },
        ["uf.*.auraSize"] = {
            desc = L["The size of the aura icons."],
            label = L["Aura size"],
        },
        ["uf.*.buffs"] = {
            choices = { L["Off"], L["Top left"], L["Top right"], L["Bottom left"], L["Bottom right"] },
            desc = L["Where the auras sit around the frame."],
            label = L["Buffs"],
        },
        ["uf.*.castPosition"] = {
            choices = { L["Above"], L["Below"] },
            desc = L["Where the cast bar sits."],
            label = L["Cast bar position"],
        },
        ["uf.*.debuffs"] = {
            choices = { L["Off"], L["Top left"], L["Top right"], L["Bottom left"], L["Bottom right"] },
            desc = L["Where the auras sit around the frame."],
            label = L["Debuffs"],
        },
        ["uf.*.healthText"] = {
            choices = { L["None"], L["Percent"], L["Value"], L["Value + Percent"] },
            desc = L["The numbers on the health bar."],
            label = L["Health text"],
        },
        ["uf.*.icons"] = {
            desc = L["Which info icons show on the frame."],
            label = L["Icons"],
        },
        ["uf.*.level"] = {
            desc = L["Show the unit's level next to its name."],
            label = L["Show level"],
        },
        ["uf.*.mirror"] = {
            desc = L["Flips the frame left to right, so it faces the player frame."],
            label = L["Mirror"],
        },
        ["uf.*.myDebuffs"] = {
            desc = L["Shows only the debuffs you cast."],
            label = L["Only my debuffs"],
        },
        ["uf.*.portrait"] = {
            choices = { L["None"], L["3D"], L["Class icon"] },
            desc = L["Show the unit's portrait (or class icon) in the frame."],
            label = L["Portrait"],
        },
        ["uf.*.powerHeight"] = {
            desc = L["0 removes the power bar."],
            label = L["Power bar height"],
        },
        ["uf.*.powerText"] = {
            desc = L["Shows numbers on the power bar."],
            label = L["Power text"],
        },
        ["uf.*.size"] = {
            desc = L["The frame's size."],
            label = L["Width · Height"],
        },
        ["uf.addonStyle"] = {
            desc = L["Switch player, target and focus frames to a more \"addon\" style, without Blizzard elements. More customizable, less Forever-like."],
            label = L["Addon style frames"],
            section = "uf.look",
            tip = L["Each style keeps its own complete setup. Switching brings settings back exactly as you left them."],
        },
        ["uf.auraShape"] = {
            choices = { L["Square"], L["Round"] },
            desc = L["The shape of the buff and debuff icons on every unit frame that uses it."],
            label = L["Aura icon shape"],
            section = "uf.auras",
        },
        ["uf.auraTimer"] = {
            choices = { L["None"], L["Under the icon"], L["Bottom of the icon"], L["Middle of the icon"] },
            desc = L["Where the time left shows on unit frame buffs and debuffs."],
            label = L["Aura timer"],
            section = "uf.auras",
        },
        ["uf.boss"] = {
            desc = L["The bosses of an encounter, mirrored like the target frame."],
            label = L["Boss frames"],
            section = "uf.frames",
        },
        ["uf.castbar"] = {
            desc = L["Your own cast bar in FlareUI style."],
            label = L["Player cast bar"],
            section = "uf.frames",
        },
        ["uf.classColours"] = {
            desc = L["Health bars in each player's class colour, on every FlareUI frame."],
            label = L["Class colours"],
            section = "uf.look",
            tip = L["Turn this off if you prefer Blizzard's default green health."],
        },
        ["uf.main"] = {
            desc = L["Player, Pet, Target and Focus Frames."],
            label = L["Main frames"],
            section = "uf.frames",
        },
        ["uf.palette"] = {
            choices = { L["FlareUI"], L["Blizzard"] },
            desc = L["The colour tones for every single FlareUI Unit Frame bar."],
            label = L["Colour palette"],
            section = "uf.look",
            tip = L["FlareUI uses softer, darker tones. Blizzard uses the game original colours."],
        },
        ["uf.party"] = {
            desc = L["Your party members, in classic or raid style."],
            label = L["Party frames"],
            section = "uf.frames",
        },
        ["uf.party.auraSize"] = {
            desc = L["The size of the aura icons."],
            label = L["Aura size"],
        },
        ["uf.party.bossDebuffs"] = {
            desc = L["Debuffs cast by bosses show larger than the rest."],
            label = L["Bigger boss debuffs"],
        },
        ["uf.party.buffs"] = {
            choices = { L["Off"], L["Right of the frame"], L["Left of the frame"], L["Above, left"], L["Above, right"], L["Below, left"], L["Below, right"], L["Inside, top left"], L["Inside, top right"], L["Inside, bottom left"], L["Inside, bottom right"] },
            desc = L["Where each kind of aura sits on or around the frame."],
            label = L["Buffs"],
        },
        ["uf.party.castbars"] = {
            desc = L["A cast bar under each member."],
            label = L["Cast bars"],
        },
        ["uf.party.debuffs"] = {
            choices = { L["Off"], L["Right of the frame"], L["Left of the frame"], L["Above, left"], L["Above, right"], L["Below, left"], L["Below, right"], L["Inside, top left"], L["Inside, top right"], L["Inside, bottom left"], L["Inside, bottom right"] },
            desc = L["Where each kind of aura sits on or around the frame."],
            label = L["Debuffs"],
        },
        ["uf.party.dispel"] = {
            choices = { L["Off"], L["Dispellable by me"], L["Dispellable by the group"] },
            desc = L["Outlines a member who has a debuff that can be dispelled."],
            label = L["Dispel highlight"],
        },
        ["uf.party.dispelIcons"] = {
            choices = { L["Off"], L["Right of the frame"], L["Left of the frame"], L["Above, left"], L["Above, right"], L["Below, left"], L["Below, right"], L["Inside, top left"], L["Inside, top right"], L["Inside, bottom left"], L["Inside, bottom right"] },
            desc = L["Where each kind of aura sits on or around the frame."],
            label = L["Dispel icons"],
        },
        ["uf.party.healerPower"] = {
            desc = L["Only healers will show a power bar."],
            label = L["Power bar for healers only"],
        },
        ["uf.party.orientation"] = {
            choices = { L["Vertical"], L["Horizontal"] },
            desc = L["Members stacked down, or side by side."],
            label = L["Orientation"],
        },
        ["uf.party.pets"] = {
            desc = L["A small frame for each pet, under its owner."],
            label = L["Pets"],
        },
        ["uf.party.showPlayer"] = {
            desc = L["Includes your own frame in the party frames."],
            label = L["Show player"],
        },
        ["uf.party.sort"] = {
            desc = L["Tank first, then healers, then damage."],
            label = L["Sort by role"],
        },
        ["uf.party.style"] = {
            choices = { L["Classic"], L["Raid"] },
            desc = L["Classic: FlareUI-like frames. Raid: compact bars."],
            label = L["Style"],
        },
        ["uf.player.fsr"] = {
            desc = L["After you spend mana, a spark crosses the bar for five seconds. Spirit regeneration comes back when it ends."],
            label = L["Five-second rule"],
        },
        ["uf.player.show"] = {
            choices = { L["Always"], L["Fade out"] },
            desc = L["Fade out: the player frame hides until you're in combat, have a target, are missing health or point at it."],
            label = L["Show Condition"],
        },
        ["uf.raid"] = {
            desc = L["Everyone in your raid, in compact tiles that stay centred as the raid grows, with main tank frames and a reminder of the buffs you can give."],
            label = L["Raid frames"],
            section = "uf.frames",
        },
        ["uf.target.classicCombo"] = {
            desc = L["Blizzard's classic combo point gems instead of FlareUI's strip."],
            label = L["Classic combo points"],
        },
        ["uf.tof"] = {
            desc = L["Who your focus is targeting."],
            label = L["Target of focus"],
            section = "uf.frames",
        },
        ["uf.tot"] = {
            desc = L["Who your target is targeting."],
            label = L["Target of target"],
            section = "uf.frames",
        },
    },
    sections = {
        ["ab.buttons"] = L["Buttons"],
        ["ab.experience"] = L["Experience"],
        ["ab.fadeOptions"] = L["Fade Options"],
        ["ab.fakeCooldownManager"] = L["Fake Cooldown Manager (FCM)"],
        ["ab.hideBlizzardElements"] = L["Hiding"],
        ["about.credits"] = L["Credits"],
        ["about.yourFriendlyUiOverhowl"] = L["Your friendly UI overhowl"],
        ["adv.reset"] = L["Reset"],
        ["ch.header"] = L["Header Buttons"],
        ["ch.howTo"] = L["How To"],
        ["dm.extras"] = L["Extras"],
        ["qol.camera"] = L["Camera"],
        ["qol.convenience"] = L["Convenience"],
        ["qol.hideClutter"] = L["Hide clutter"],
        ["qol.looting"] = L["Looting"],
        ["qol.nameplates"] = L["Nameplates"],
        ["qol.syncBlizzUi"] = L["Sync Blizz UI"],
        ["qol.vendor"] = L["Vendor"],
        ["qol.windows"] = L["Windows"],
        ["qt.minimizeIn"] = L["Minimize in"],
        ["rb.bars"] = L["Bars"],
        ["rm.controller"] = L["Controller"],
        ["rm.look"] = L["Look"],
        ["rm.radialMacros"] = L["Radial macros"],
        ["tt.showTooltips"] = L["Show tooltips"],
        ["uf.auras"] = L["Auras"],
        ["uf.frames"] = L["Enable Frames"],
        ["uf.look"] = L["Look"],
    },
    window = {
        editModeButtonOnAFrameRow = L["Edit"],
        editModeDialogsBackLink = L["FlareUI settings"],
        leftListGroups = L["HUD"],
        leftListGroups2 = L["Info"],
        leftListGroups3 = L["Tools"],
        moduleOffCard = L["{Module} is off. Its settings appear here once it's on."],
        moduleOffCard2 = L["Turn on"],
        noResults = L["No settings match."],
        reloadFooter = L["{n} change(s) need a reload"],
        reloadFooter2 = L["Reload now"],
        reloadOnClose = L["Some changes need a reload to take effect."],
        reloadOnClose2 = L["Reload now"],
        reloadOnClose3 = L["Later"],
        searchPlaceholder = L["Search settings"],
        tabs = L["Settings"],
        tabs2 = L["What's new"],
        title = L["FlareUI"],
    },
}
