// Builds Settings/WhatsNew.lua from CHANGELOG.md: the latest versions' notes, already formatted for
// the settings panel's What's new tab (gold headings, bullets, white bold).
//   node tools/changelog2lua.js [versions to keep, default 5]
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const KEEP = Number(process.argv[2]) || 5;
const lines = fs.readFileSync(path.join(ROOT, 'CHANGELOG.md'), 'utf8').split(/\r?\n/);

const versions = [];
let current = null;
for (const raw of lines) {
  const m = raw.match(/^# FlareUI (\S+)/);
  if (m) {
    if (versions.length >= KEEP) break;
    current = { version: m[1], text: [] };
    versions.push(current);
    continue;
  }
  if (!current) continue;
  let line = raw.trimEnd();
  line = line.replace(/\*\*(.+?)\*\*/g, '|cffffffff$1|r');          // bold: white
  line = line.replace(/`([^`]+)`/g, '|cffffd100$1|r');               // code: gold
  if (/^## /.test(line)) line = '|cffffd100' + line.slice(3) + '|r'; // section: gold
  else if (/^\s+- /.test(line)) line = '      - ' + line.replace(/^\s+- /, '');
  else if (/^- /.test(line)) line = '• ' + line.slice(2);
  current.text.push(line);
}

const quote = (s) => '"' + s.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n') + '"';
const out = [
  '-- What\'s new: the latest versions\' notes for the settings panel.',
  '-- GENERATED by tools/changelog2lua.js from CHANGELOG.md; do not edit by hand.',
  'local _, ns = ...',
  '',
  'ns.WhatsNew = {',
];
for (const v of versions) {
  const text = v.text.join('\n').replace(/\n{3,}/g, '\n\n').trim();
  out.push(`    { version = ${quote(v.version)}, text = ${quote(text)} },`);
}
out.push('}', '');
fs.writeFileSync(path.join(ROOT, 'Settings/WhatsNew.lua'), out.join('\n'));
console.log(`WhatsNew.lua: ${versions.map((v) => v.version).join(', ')}`);
